Accepts Vector of Inputs
paloukari/TypeEdge.AnomalyDetection pull request #17
Opened 2018-07-05 22:42 UTC by ecthros

Visualizer now accepts a vector of inputs, rather than a single value. This allows it to take n-dimensional data. 

Also fixed the memory leak caused by Google Charts.

2018-07-05 23:09 UTC, paloukari requested changes

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/FFT.cs
> +namespace sendInfo
Please use namespace names that align with the rest of the app

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/Message.cs
> +    class Message
All messages are defined in the shared class library project to avoid cross module references.
Also, please consider not duplicating the original information. If needed, feel free to augment the existing message type

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/Message.cs
> +        public class NewValue
Please define one class per file

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/SeasonSubtract.cs
> +        //public void TrainPeriod(double[] fftResults) {
please do not check in temp code or commented out code

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/TemperatureSensor.cs
> +            comps[0] = new WaveConfig(WaveType.Sine, 0.0001, 70);
please avoid hard coded config info. You can use the module twin to configure the generator.

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/TemperatureSensor.cs
> +            FFT fft = new FFT(128, 10);
please isolate the FFT functionality to a dedicated new module

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/TemperatureSensor.cs
> +                var newValue = g.Read();
please name all variables in a way that a non-familiar with the project reader can understand the purpose&function of the variable

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/TemperatureSensor.cs
> +                m.SubtractionGraphResult = new double[128];
please avoid hard coded config values

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/TemperatureSensor.cs
> +                await Task.Delay(100);
please avoid hard coded config values

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/TemperatureSensor.csproj
> +    <PackageReference Include="MathNet.Numerics" Version="4.5.1" />
please make sure that these packages are dotnet standard libraries. In other words, the app can run in Linux

2018-07-05 23:09 UTC, paloukari commented on Modules/VisualizationWeb/wwwroot/js/visualizer.js
> +    //console.log(numToDraw);
Avoid checking in commented out code

2018-07-05 23:09 UTC, paloukari commented on Modules/VisualizationWeb/wwwroot/js/visualizer.js
> +var chart1 = "";
please investigate if the number of charts can be dynamic

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/Message.cs
> +        public NewValue NewVal = new NewValue();
find a more generic way to describe the data and feed the data in the visualizer, so next time we add more data to the flow, we won't have to refactor this

2018-07-05 23:09 UTC, paloukari commented on Modules/TemperatureSensor/SeasonSubtract.cs
> +    class SeasonSubtract
Please decouple the FFT with the seasonality processing. These two logical actions are not necessarily always correlated

2018-07-06 18:06 UTC, ecthros commented
Please wait to merge until we have FFT fully working on sending side and removed from JavaScript

2018-07-13 18:31 UTC, closed without merging